// Central icon registry: adding a platform = one entry in each map below
// (plus the union member in social-types.ts). Nothing else in the app should
// import platform icons directly.

import type { IconType } from "react-icons";
import {
  FaDiscord,
  FaEnvelope,
  FaFacebook,
  FaGithub,
  FaGlobe,
  FaHeart,
  FaInstagram,
  FaLinkedin,
  FaLock,
  FaPatreon,
  FaPhone,
  FaReddit,
  FaSnapchat,
  FaSoundcloud,
  FaSpotify,
  FaStar,
  FaTelegram,
  FaThreads,
  FaTiktok,
  FaTwitch,
  FaWhatsapp,
  FaXTwitter,
  FaYoutube,
} from "react-icons/fa6";
import { SiApplemusic, SiKick, SiOnlyfans } from "react-icons/si";
import type { SocialPlatform } from "./social-types";

export const SOCIAL_ICONS: Record<SocialPlatform, IconType> = {
  instagram: FaInstagram,
  x: FaXTwitter,
  threads: FaThreads,
  facebook: FaFacebook,
  youtube: FaYoutube,
  tiktok: FaTiktok,
  discord: FaDiscord,
  telegram: FaTelegram,
  whatsapp: FaWhatsapp,
  spotify: FaSpotify,
  applemusic: SiApplemusic,
  soundcloud: FaSoundcloud,
  snapchat: FaSnapchat,
  linkedin: FaLinkedin,
  github: FaGithub,
  reddit: FaReddit,
  twitch: FaTwitch,
  kick: SiKick,
  patreon: FaPatreon,
  onlyfans: SiOnlyfans,
  // No official Fansly/Fanvue glyph ships in react-icons yet — stand-ins that
  // read correctly at button size. Swap here once real glyphs are available.
  fansly: FaHeart,
  fanvue: FaStar,
  website: FaGlobe,
  email: FaEnvelope,
  phone: FaPhone,
  // Semantic "locked / VIP" link — shows a padlock instead of a network glyph.
  lock: FaLock,
};

export const PLATFORM_LABELS: Record<SocialPlatform, string> = {
  instagram: "Instagram",
  x: "X (Twitter)",
  threads: "Threads",
  facebook: "Facebook",
  youtube: "YouTube",
  tiktok: "TikTok",
  discord: "Discord",
  telegram: "Telegram",
  whatsapp: "WhatsApp",
  spotify: "Spotify",
  applemusic: "Apple Music",
  soundcloud: "SoundCloud",
  snapchat: "Snapchat",
  linkedin: "LinkedIn",
  github: "GitHub",
  reddit: "Reddit",
  twitch: "Twitch",
  kick: "Kick",
  patreon: "Patreon",
  onlyfans: "OnlyFans",
  fansly: "Fansly",
  fanvue: "Fanvue",
  website: "Website",
  email: "Email",
  phone: "Phone",
  lock: "Locked",
};

// Official brand accents, used for HOVER effects only — the resting state
// stays monochrome to match the luxury theme. Dark-brand marks (X, Threads,
// GitHub) and the non-brand contact platforms fall back to white.
export const BRAND_COLORS: Record<SocialPlatform, string> = {
  instagram: "#E4405F",
  x: "#FFFFFF",
  threads: "#FFFFFF",
  facebook: "#0866FF",
  youtube: "#FF0000",
  tiktok: "#4DE8F4",
  discord: "#5865F2",
  telegram: "#26A5E4",
  whatsapp: "#25D366",
  spotify: "#1DB954",
  applemusic: "#FA243C",
  soundcloud: "#FF5500",
  snapchat: "#FFFC00",
  linkedin: "#0A66C2",
  github: "#FFFFFF",
  reddit: "#FF4500",
  twitch: "#9146FF",
  kick: "#53FC18",
  patreon: "#FF424D",
  onlyfans: "#00AFF0",
  fansly: "#2699F6",
  fanvue: "#FFFFFF",
  website: "#FFFFFF",
  email: "#FFFFFF",
  phone: "#FFFFFF",
  lock: "#FFFFFF",
};
