/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThetejedaRouteImport } from './routes/thetejeda'
import { Route as TdRouteImport } from './routes/td'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EldondollaRouteImport } from './routes/eldondolla'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DanielasanchezRouteImport } from './routes/danielasanchez'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as DocsSystemRouteImport } from './routes/docs.system'
import { Route as DocsDataModelRouteImport } from './routes/docs.data-model'
import { Route as DashboardSubscribersRouteImport } from './routes/dashboard.subscribers'
import { Route as DashboardStorefrontRouteImport } from './routes/dashboard.storefront'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPostsRouteImport } from './routes/dashboard.posts'
import { Route as DashboardPerformanceRouteImport } from './routes/dashboard.performance'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardMediaKitRouteImport } from './routes/dashboard.media-kit'
import { Route as DashboardLinksRouteImport } from './routes/dashboard.links'
import { Route as DashboardLinkInBioRouteImport } from './routes/dashboard.link-in-bio'
import { Route as DashboardHomeRouteImport } from './routes/dashboard.home'
import { Route as DashboardEarningsRouteImport } from './routes/dashboard.earnings'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminLedgerRouteImport } from './routes/admin.ledger'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminCreatorsRouteImport } from './routes/admin.creators'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ApiWebhooksStreamRouteImport } from './routes/api.webhooks.stream'
import { Route as AdminLedgerTransactionIdRouteImport } from './routes/admin.ledger.$transactionId'
import { Route as AdminCreatorsNewRouteImport } from './routes/admin.creators.new'
import { Route as AdminCreatorsCreatorProfileIdRouteImport } from './routes/admin.creators.$creatorProfileId'

const ThetejedaRoute = ThetejedaRouteImport.update({
  id: '/thetejeda',
  path: '/thetejeda',
  getParentRoute: () => rootRouteImport,
} as any)
const TdRoute = TdRouteImport.update({
  id: '/td',
  path: '/td',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EldondollaRoute = EldondollaRouteImport.update({
  id: '/eldondolla',
  path: '/eldondolla',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DanielasanchezRoute = DanielasanchezRouteImport.update({
  id: '/danielasanchez',
  path: '/danielasanchez',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const DocsSystemRoute = DocsSystemRouteImport.update({
  id: '/docs/system',
  path: '/docs/system',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDataModelRoute = DocsDataModelRouteImport.update({
  id: '/docs/data-model',
  path: '/docs/data-model',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubscribersRoute = DashboardSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStorefrontRoute = DashboardStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostsRoute = DashboardPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerformanceRoute = DashboardPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMediaKitRoute = DashboardMediaKitRouteImport.update({
  id: '/media-kit',
  path: '/media-kit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinksRoute = DashboardLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinkInBioRoute = DashboardLinkInBioRouteImport.update({
  id: '/link-in-bio',
  path: '/link-in-bio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEarningsRoute = DashboardEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLedgerRoute = AdminLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreatorsRoute = AdminCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWebhooksStreamRoute = ApiWebhooksStreamRouteImport.update({
  id: '/api/webhooks/stream',
  path: '/api/webhooks/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLedgerTransactionIdRoute =
  AdminLedgerTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => AdminLedgerRoute,
  } as any)
const AdminCreatorsNewRoute = AdminCreatorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCreatorsRoute,
} as any)
const AdminCreatorsCreatorProfileIdRoute =
  AdminCreatorsCreatorProfileIdRouteImport.update({
    id: '/$creatorProfileId',
    path: '/$creatorProfileId',
    getParentRoute: () => AdminCreatorsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/danielasanchez': typeof DanielasanchezRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/discover': typeof DiscoverRoute
  '/eldondolla': typeof EldondollaRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/td': typeof TdRoute
  '/thetejeda': typeof ThetejedaRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/creators': typeof AdminCreatorsRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/ledger': typeof AdminLedgerRouteWithChildren
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/link-in-bio': typeof DashboardLinkInBioRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/media-kit': typeof DashboardMediaKitRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storefront': typeof DashboardStorefrontRoute
  '/dashboard/subscribers': typeof DashboardSubscribersRoute
  '/docs/data-model': typeof DocsDataModelRoute
  '/docs/system': typeof DocsSystemRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/creators/$creatorProfileId': typeof AdminCreatorsCreatorProfileIdRoute
  '/admin/creators/new': typeof AdminCreatorsNewRoute
  '/admin/ledger/$transactionId': typeof AdminLedgerTransactionIdRoute
  '/api/webhooks/stream': typeof ApiWebhooksStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/danielasanchez': typeof DanielasanchezRoute
  '/demo': typeof DemoRoute
  '/discover': typeof DiscoverRoute
  '/eldondolla': typeof EldondollaRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/td': typeof TdRoute
  '/thetejeda': typeof ThetejedaRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/creators': typeof AdminCreatorsRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/ledger': typeof AdminLedgerRouteWithChildren
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/link-in-bio': typeof DashboardLinkInBioRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/media-kit': typeof DashboardMediaKitRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storefront': typeof DashboardStorefrontRoute
  '/dashboard/subscribers': typeof DashboardSubscribersRoute
  '/docs/data-model': typeof DocsDataModelRoute
  '/docs/system': typeof DocsSystemRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/creators/$creatorProfileId': typeof AdminCreatorsCreatorProfileIdRoute
  '/admin/creators/new': typeof AdminCreatorsNewRoute
  '/admin/ledger/$transactionId': typeof AdminLedgerTransactionIdRoute
  '/api/webhooks/stream': typeof ApiWebhooksStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/danielasanchez': typeof DanielasanchezRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/discover': typeof DiscoverRoute
  '/eldondolla': typeof EldondollaRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/td': typeof TdRoute
  '/thetejeda': typeof ThetejedaRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/creators': typeof AdminCreatorsRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/ledger': typeof AdminLedgerRouteWithChildren
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/link-in-bio': typeof DashboardLinkInBioRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/media-kit': typeof DashboardMediaKitRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storefront': typeof DashboardStorefrontRoute
  '/dashboard/subscribers': typeof DashboardSubscribersRoute
  '/docs/data-model': typeof DocsDataModelRoute
  '/docs/system': typeof DocsSystemRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/creators/$creatorProfileId': typeof AdminCreatorsCreatorProfileIdRoute
  '/admin/creators/new': typeof AdminCreatorsNewRoute
  '/admin/ledger/$transactionId': typeof AdminLedgerTransactionIdRoute
  '/api/webhooks/stream': typeof ApiWebhooksStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/account'
    | '/admin'
    | '/danielasanchez'
    | '/dashboard'
    | '/demo'
    | '/discover'
    | '/eldondolla'
    | '/feed'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/td'
    | '/thetejeda'
    | '/admin/audit'
    | '/admin/creators'
    | '/admin/finance'
    | '/admin/ledger'
    | '/admin/payouts'
    | '/admin/reports'
    | '/auth/callback'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/home'
    | '/dashboard/link-in-bio'
    | '/dashboard/links'
    | '/dashboard/media-kit'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/performance'
    | '/dashboard/posts'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/storefront'
    | '/dashboard/subscribers'
    | '/docs/data-model'
    | '/docs/system'
    | '/messages/$conversationId'
    | '/post/$postId'
    | '/dashboard/'
    | '/admin/creators/$creatorProfileId'
    | '/admin/creators/new'
    | '/admin/ledger/$transactionId'
    | '/api/webhooks/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/account'
    | '/admin'
    | '/danielasanchez'
    | '/demo'
    | '/discover'
    | '/eldondolla'
    | '/feed'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/td'
    | '/thetejeda'
    | '/admin/audit'
    | '/admin/creators'
    | '/admin/finance'
    | '/admin/ledger'
    | '/admin/payouts'
    | '/admin/reports'
    | '/auth/callback'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/home'
    | '/dashboard/link-in-bio'
    | '/dashboard/links'
    | '/dashboard/media-kit'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/performance'
    | '/dashboard/posts'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/storefront'
    | '/dashboard/subscribers'
    | '/docs/data-model'
    | '/docs/system'
    | '/messages/$conversationId'
    | '/post/$postId'
    | '/dashboard'
    | '/admin/creators/$creatorProfileId'
    | '/admin/creators/new'
    | '/admin/ledger/$transactionId'
    | '/api/webhooks/stream'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/account'
    | '/admin'
    | '/danielasanchez'
    | '/dashboard'
    | '/demo'
    | '/discover'
    | '/eldondolla'
    | '/feed'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/td'
    | '/thetejeda'
    | '/admin/audit'
    | '/admin/creators'
    | '/admin/finance'
    | '/admin/ledger'
    | '/admin/payouts'
    | '/admin/reports'
    | '/auth/callback'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/home'
    | '/dashboard/link-in-bio'
    | '/dashboard/links'
    | '/dashboard/media-kit'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/performance'
    | '/dashboard/posts'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/storefront'
    | '/dashboard/subscribers'
    | '/docs/data-model'
    | '/docs/system'
    | '/messages/$conversationId'
    | '/post/$postId'
    | '/dashboard/'
    | '/admin/creators/$creatorProfileId'
    | '/admin/creators/new'
    | '/admin/ledger/$transactionId'
    | '/api/webhooks/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  DanielasanchezRoute: typeof DanielasanchezRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  DiscoverRoute: typeof DiscoverRoute
  EldondollaRoute: typeof EldondollaRoute
  FeedRoute: typeof FeedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TdRoute: typeof TdRoute
  ThetejedaRoute: typeof ThetejedaRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DocsDataModelRoute: typeof DocsDataModelRoute
  DocsSystemRoute: typeof DocsSystemRoute
  PostPostIdRoute: typeof PostPostIdRoute
  ApiWebhooksStreamRoute: typeof ApiWebhooksStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thetejeda': {
      id: '/thetejeda'
      path: '/thetejeda'
      fullPath: '/thetejeda'
      preLoaderRoute: typeof ThetejedaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/td': {
      id: '/td'
      path: '/td'
      fullPath: '/td'
      preLoaderRoute: typeof TdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eldondolla': {
      id: '/eldondolla'
      path: '/eldondolla'
      fullPath: '/eldondolla'
      preLoaderRoute: typeof EldondollaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danielasanchez': {
      id: '/danielasanchez'
      path: '/danielasanchez'
      fullPath: '/danielasanchez'
      preLoaderRoute: typeof DanielasanchezRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/docs/system': {
      id: '/docs/system'
      path: '/docs/system'
      fullPath: '/docs/system'
      preLoaderRoute: typeof DocsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/data-model': {
      id: '/docs/data-model'
      path: '/docs/data-model'
      fullPath: '/docs/data-model'
      preLoaderRoute: typeof DocsDataModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subscribers': {
      id: '/dashboard/subscribers'
      path: '/subscribers'
      fullPath: '/dashboard/subscribers'
      preLoaderRoute: typeof DashboardSubscribersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/storefront': {
      id: '/dashboard/storefront'
      path: '/storefront'
      fullPath: '/dashboard/storefront'
      preLoaderRoute: typeof DashboardStorefrontRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/posts': {
      id: '/dashboard/posts'
      path: '/posts'
      fullPath: '/dashboard/posts'
      preLoaderRoute: typeof DashboardPostsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/performance': {
      id: '/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/media-kit': {
      id: '/dashboard/media-kit'
      path: '/media-kit'
      fullPath: '/dashboard/media-kit'
      preLoaderRoute: typeof DashboardMediaKitRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/links': {
      id: '/dashboard/links'
      path: '/links'
      fullPath: '/dashboard/links'
      preLoaderRoute: typeof DashboardLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/link-in-bio': {
      id: '/dashboard/link-in-bio'
      path: '/link-in-bio'
      fullPath: '/dashboard/link-in-bio'
      preLoaderRoute: typeof DashboardLinkInBioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/earnings': {
      id: '/dashboard/earnings'
      path: '/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof DashboardEarningsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ledger': {
      id: '/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AdminLedgerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creators': {
      id: '/admin/creators'
      path: '/creators'
      fullPath: '/admin/creators'
      preLoaderRoute: typeof AdminCreatorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhooks/stream': {
      id: '/api/webhooks/stream'
      path: '/api/webhooks/stream'
      fullPath: '/api/webhooks/stream'
      preLoaderRoute: typeof ApiWebhooksStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ledger/$transactionId': {
      id: '/admin/ledger/$transactionId'
      path: '/$transactionId'
      fullPath: '/admin/ledger/$transactionId'
      preLoaderRoute: typeof AdminLedgerTransactionIdRouteImport
      parentRoute: typeof AdminLedgerRoute
    }
    '/admin/creators/new': {
      id: '/admin/creators/new'
      path: '/new'
      fullPath: '/admin/creators/new'
      preLoaderRoute: typeof AdminCreatorsNewRouteImport
      parentRoute: typeof AdminCreatorsRoute
    }
    '/admin/creators/$creatorProfileId': {
      id: '/admin/creators/$creatorProfileId'
      path: '/$creatorProfileId'
      fullPath: '/admin/creators/$creatorProfileId'
      preLoaderRoute: typeof AdminCreatorsCreatorProfileIdRouteImport
      parentRoute: typeof AdminCreatorsRoute
    }
  }
}

interface AdminCreatorsRouteChildren {
  AdminCreatorsCreatorProfileIdRoute: typeof AdminCreatorsCreatorProfileIdRoute
  AdminCreatorsNewRoute: typeof AdminCreatorsNewRoute
}

const AdminCreatorsRouteChildren: AdminCreatorsRouteChildren = {
  AdminCreatorsCreatorProfileIdRoute: AdminCreatorsCreatorProfileIdRoute,
  AdminCreatorsNewRoute: AdminCreatorsNewRoute,
}

const AdminCreatorsRouteWithChildren = AdminCreatorsRoute._addFileChildren(
  AdminCreatorsRouteChildren,
)

interface AdminLedgerRouteChildren {
  AdminLedgerTransactionIdRoute: typeof AdminLedgerTransactionIdRoute
}

const AdminLedgerRouteChildren: AdminLedgerRouteChildren = {
  AdminLedgerTransactionIdRoute: AdminLedgerTransactionIdRoute,
}

const AdminLedgerRouteWithChildren = AdminLedgerRoute._addFileChildren(
  AdminLedgerRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCreatorsRoute: typeof AdminCreatorsRouteWithChildren
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminLedgerRoute: typeof AdminLedgerRouteWithChildren
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminReportsRoute: typeof AdminReportsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCreatorsRoute: AdminCreatorsRouteWithChildren,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminLedgerRoute: AdminLedgerRouteWithChildren,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminReportsRoute: AdminReportsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardEarningsRoute: typeof DashboardEarningsRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardLinkInBioRoute: typeof DashboardLinkInBioRoute
  DashboardLinksRoute: typeof DashboardLinksRoute
  DashboardMediaKitRoute: typeof DashboardMediaKitRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPerformanceRoute: typeof DashboardPerformanceRoute
  DashboardPostsRoute: typeof DashboardPostsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStorefrontRoute: typeof DashboardStorefrontRoute
  DashboardSubscribersRoute: typeof DashboardSubscribersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardEarningsRoute: DashboardEarningsRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardLinkInBioRoute: DashboardLinkInBioRoute,
  DashboardLinksRoute: DashboardLinksRoute,
  DashboardMediaKitRoute: DashboardMediaKitRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPerformanceRoute: DashboardPerformanceRoute,
  DashboardPostsRoute: DashboardPostsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStorefrontRoute: DashboardStorefrontRoute,
  DashboardSubscribersRoute: DashboardSubscribersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  DanielasanchezRoute: DanielasanchezRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  DiscoverRoute: DiscoverRoute,
  EldondollaRoute: EldondollaRoute,
  FeedRoute: FeedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TdRoute: TdRoute,
  ThetejedaRoute: ThetejedaRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DocsDataModelRoute: DocsDataModelRoute,
  DocsSystemRoute: DocsSystemRoute,
  PostPostIdRoute: PostPostIdRoute,
  ApiWebhooksStreamRoute: ApiWebhooksStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
